import {
  ActivityIcon,
  BarChart3Icon,
  BellIcon,
  BuildingIcon,
  CalendarDaysIcon,
  CalendarIcon,
  ClockIcon,
  FileIcon,
  FolderOpenIcon,
  HandHeartIcon,
  HistoryIcon,
  LayoutDashboardIcon,
  LifeBuoyIcon,
  ListChecksIcon,
  MessageSquareIcon,
  NetworkIcon,
  PencilIcon,
  PlusIcon,
  SettingsIcon,
  ShieldCheckIcon,
  ShieldUserIcon,
  UploadIcon,
  UserIcon,
  UserRoundIcon,
  UsersIcon,
  WalletIcon,
  type LucideIcon,
} from "lucide-react";

/** Bildet StaticRegistryEntry.iconKey / SearchResultItem.iconKey auf das lucide-react-Symbol ab. */
export const ICON_MAP: Record<string, LucideIcon> = {
  activity: ActivityIcon,
  "bar-chart-3": BarChart3Icon,
  bell: BellIcon,
  building: BuildingIcon,
  calendar: CalendarIcon,
  "calendar-days": CalendarDaysIcon,
  clock: ClockIcon,
  dashboard: LayoutDashboardIcon,
  file: FileIcon,
  "folder-open": FolderOpenIcon,
  "hand-heart": HandHeartIcon,
  history: HistoryIcon,
  "life-buoy": LifeBuoyIcon,
  "list-checks": ListChecksIcon,
  "message-square": MessageSquareIcon,
  network: NetworkIcon,
  pencil: PencilIcon,
  plus: PlusIcon,
  settings: SettingsIcon,
  "shield-check": ShieldCheckIcon,
  "shield-user": ShieldUserIcon,
  upload: UploadIcon,
  user: UserIcon,
  "user-round": UserRoundIcon,
  users: UsersIcon,
  wallet: WalletIcon,
};

export function ResultIcon({ iconKey, className }: { iconKey: string; className?: string }) {
  const Icon = ICON_MAP[iconKey] ?? FileIcon;
  return <Icon className={className} aria-hidden="true" />;
}
