import type { StaticRegistryEntry } from "./types";

/**
 * Statischer Katalog der zentralen Suche (Strg/⌘+K): Aktionen und Seiten.
 *
 * Läuft bewusst PARALLEL zu src/components/layout/nav.tsx (dort nur die Top-Level-Menüpunkte für
 * die Seitenleiste) – die Suche braucht zusätzlich Unterseiten (anlegen/bearbeiten/importieren),
 * Kurzbeschreibungen und Suchbegriffe, die NavDefinition nicht trägt. Beim Hinzufügen einer neuen
 * Seite bitte auch hier ergänzen, sonst findet die Suche sie nicht.
 *
 * `permission` entspricht exakt dem PermissionKey, den die Zielseite selbst prüft (siehe jeweilige
 * page.tsx) – so zeigt die Suche nie mehr, als die Seite ohnehin erlauben würde.
 */
export const SEARCH_REGISTRY: StaticRegistryEntry[] = [
  // Aktionen ------------------------------------------------------------------------------------
  {
    id: "action:mitglied-hinzufuegen",
    category: "aktionen",
    title: "Mitglied hinzufügen",
    description: "Neues Mitglied anlegen",
    href: "/mitglieder/neu",
    iconKey: "plus",
    permission: "members:create",
    keywords: ["neu", "anlegen"],
  },
  {
    id: "action:veranstaltung-erstellen",
    category: "aktionen",
    title: "Veranstaltung erstellen",
    description: "Neue Veranstaltung anlegen",
    href: "/veranstaltungen/neu",
    iconKey: "plus",
    permission: "events:create",
    keywords: ["neu", "anlegen"],
  },
  {
    id: "action:mitglieder-importieren",
    category: "aktionen",
    title: "Mitglieder importieren",
    description: "Mitglieder per CSV-Datei importieren",
    href: "/mitglieder/import",
    iconKey: "upload",
    permission: "members:import",
    keywords: ["csv", "import"],
  },
  {
    id: "action:nachricht-schreiben",
    category: "aktionen",
    title: "Nachricht schreiben",
    description: "Neue Nachricht verfassen und versenden",
    href: "/nachrichten/neu",
    iconKey: "message-square",
    permission: "messages:send",
    keywords: ["neu", "senden"],
  },
  {
    id: "action:helferplan-oeffnen",
    category: "aktionen",
    title: "Helferplan öffnen",
    description: "Übersicht offener und eigener Helferschichten",
    href: "/helferplanung",
    iconKey: "hand-heart",
    permission: "shifts:read",
    keywords: ["schicht", "helferstunden"],
  },
  {
    id: "action:schicht-bearbeiten",
    category: "aktionen",
    title: "Schicht bearbeiten",
    description: "Zur Helferplanung wechseln und eine Schicht bearbeiten",
    href: "/helferplanung",
    iconKey: "pencil",
    permission: "shifts:manage",
    keywords: ["helferschicht"],
  },

  // Seiten – Auswertungen (mehrere eigenständige Ziele statt eines mehrdeutigen "Auswertung") ---
  {
    id: "page:mitgliederstatistik",
    category: "seiten",
    title: "Auswertung anzeigen · Mitgliederstatistik",
    description: "Mitgliederzahlen und Verteilung auswerten",
    href: "/mitglieder/statistik",
    iconKey: "bar-chart-3",
    permission: "members:read",
    keywords: ["auswertung", "statistik"],
  },
  {
    id: "page:helferstunden",
    category: "seiten",
    title: "Auswertung anzeigen · Helferstunden",
    description: "Geleistete Helferstunden ansehen und bestätigen",
    href: "/helferplanung/stunden",
    iconKey: "clock",
    permission: "shifts:read",
    keywords: ["auswertung"],
  },
  {
    id: "page:dashboard-aktivitaet",
    category: "seiten",
    title: "Auswertung anzeigen · Vereinsaktivität",
    description: "Aktivitäts-Auswertung im Dashboard",
    href: "/dashboard?tab=aktivitaet",
    iconKey: "activity",
    keywords: ["auswertung", "dashboard"],
  },

  // Seiten – Übersicht und Verwaltung ------------------------------------------------------------
  {
    id: "page:dashboard",
    category: "seiten",
    title: "Dashboard",
    description: "Übersicht mit Kennzahlen, Terminen und offenen Aufgaben",
    href: "/dashboard",
    iconKey: "dashboard",
  },
  {
    id: "page:mitglieder",
    category: "seiten",
    title: "Mitglieder",
    description: "Mitgliederliste ansehen, suchen und filtern",
    href: "/mitglieder",
    iconKey: "users",
    permission: "members:read",
    notOwnOnly: true,
  },
  {
    id: "page:kalender",
    category: "seiten",
    title: "Kalender",
    description: "Termine und Veranstaltungen im Kalender ansehen",
    href: "/kalender",
    iconKey: "calendar",
    permission: "events:read",
    // Hieß im Menü früher „Termine“ – wer danach sucht, soll den Kalender weiter finden.
    keywords: ["termine"],
  },
  {
    id: "page:veranstaltungen",
    category: "seiten",
    title: "Veranstaltungen",
    description: "Veranstaltungen ansehen und verwalten",
    href: "/veranstaltungen",
    iconKey: "calendar-days",
    permission: "events:read",
  },
  {
    id: "page:helferplanung",
    category: "seiten",
    title: "Helferplanung",
    description: "In offene Schichten eintragen und eigene Einsätze im Blick behalten",
    href: "/helferplanung",
    iconKey: "hand-heart",
    permission: "shifts:read",
    // Hieß im Menü früher „Helferstunden“; die Stunden selbst hat die Unterseite „Helferstunden“ (oben).
    keywords: ["schichten", "helferstunden"],
  },
  {
    id: "page:helferplanung-drucken",
    category: "seiten",
    title: "Helferplan drucken",
    description: "Helferplan als Druckansicht öffnen",
    href: "/helferplanung/drucken",
    iconKey: "hand-heart",
    permission: "shifts:read",
    keywords: ["drucken", "pdf"],
  },
  {
    id: "page:abteilungen",
    category: "seiten",
    title: "Abteilungen",
    description: "Abteilungen und Gruppen des Vereins ansehen",
    href: "/abteilungen",
    iconKey: "network",
    permission: "departments:read",
  },
  {
    id: "page:aufgaben",
    category: "seiten",
    title: "Aufgaben",
    description: "Aufgaben und Checklisten verwalten",
    href: "/aufgaben",
    iconKey: "list-checks",
    permission: "tasks:read",
  },
  {
    id: "page:dokumente",
    category: "seiten",
    title: "Dokumente",
    description: "Dokumente ansehen und herunterladen",
    href: "/dokumente",
    iconKey: "folder-open",
    permission: "documents:read",
  },
  {
    id: "page:nachrichten",
    category: "seiten",
    title: "Nachrichten",
    description: "Ein- und ausgehende Nachrichten ansehen",
    href: "/nachrichten",
    iconKey: "message-square",
    permission: "messages:read",
  },
  {
    id: "page:benachrichtigungen",
    category: "seiten",
    title: "Benachrichtigungen",
    description: "Ungelesene und bisherige Benachrichtigungen ansehen",
    href: "/benachrichtigungen",
    iconKey: "bell",
  },
  {
    id: "page:benutzer",
    category: "seiten",
    title: "Benutzer und Rollen",
    description: "Benutzerkonten und Rollen verwalten",
    href: "/benutzer",
    iconKey: "shield-check",
    permission: "users:read",
  },
  {
    id: "page:einstellungen",
    category: "seiten",
    title: "Vereinseinstellungen",
    description: "Stammdaten, Logo und Einstellungen des Vereins bearbeiten",
    href: "/einstellungen",
    iconKey: "settings",
    permission: "club:update",
    keywords: ["logo", "wappen", "vereinslogo"],
  },
  {
    id: "page:protokoll",
    category: "seiten",
    title: "Änderungsprotokoll",
    description: "Änderungen und Aktionen im Verein nachvollziehen",
    href: "/protokoll",
    iconKey: "history",
    permission: "audit:read",
  },
  {
    id: "page:profil",
    category: "seiten",
    title: "Mein Profil",
    description: "Eigene Kontodaten, Passwort und Sitzungen verwalten",
    href: "/profil",
    iconKey: "user-round",
  },
  {
    id: "page:datenschutz",
    category: "seiten",
    title: "Datenschutz",
    description: "Eigene Einwilligungen und Datenschutzanfragen verwalten",
    href: "/datenschutz",
    iconKey: "shield-user",
  },
  {
    id: "page:hilfe",
    category: "seiten",
    title: "Hilfe & Support",
    description: "Hilfe, FAQ und Support-Kontakte",
    href: "/hilfe",
    iconKey: "life-buoy",
  },
  {
    id: "page:hilfe-meldungen",
    category: "seiten",
    title: "Eingegangene Meldungen",
    description: "Eingegangene Support-Meldungen bearbeiten",
    href: "/hilfe/meldungen",
    iconKey: "life-buoy",
    permission: "club:update",
  },
  {
    id: "page:system",
    category: "seiten",
    title: "Systemadministration",
    description: "Vereine und Benutzerkonten der Plattform verwalten",
    href: "/system",
    iconKey: "building",
    platformAdminOnly: true,
  },
];
